### Задание на повторение материала

In [1]:
import numpy as np

#### 1

In [3]:
a = np.array(range(12, 24))
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2

In [12]:
a1 = a.reshape(2, 6)
a2 = a.reshape(3, 4)
a3 = a.reshape(4, 3)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)
a1, a2, a3, a4, a5

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

#### 3

In [23]:
a11 = a.reshape(2, -1)
a12 = a.reshape(3, -1)
a13 = a.reshape(4, -1)
a14 = a.reshape(-1, 2)
a15 = a.reshape(-1, 1)
a11, a12, a13, a14, a15

(array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

#### 4

In [20]:
a.shape

(12,)

In [21]:
a5.shape

(12, 1)

In [24]:
a15.shape

(12, 1)

##### Массивы a5 и a15 нельзя назвать одномерными

#### 5

In [34]:
L = np.random.randn(3, 4)
L, L.size

(array([[ 1.56804232, -0.73677091,  2.09745702, -0.2958728 ],
        [ 1.42538405, -0.75234791, -0.79721586,  0.01336434],
        [-1.04211774, -1.53596552, -0.33745848,  0.66890256]]),
 12)

In [36]:
M = L.flatten()
M, M.size

(array([ 1.56804232, -0.73677091,  2.09745702, -0.2958728 ,  1.42538405,
        -0.75234791, -0.79721586,  0.01336434, -1.04211774, -1.53596552,
        -0.33745848,  0.66890256]),
 12)

#### 6

In [43]:
A = np.arange(20, 0, -2)
A

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 7

In [49]:
B = np.arange(20, 0, -2)
B.resize(1, 10)
B

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

##### Массив A - одномерный B - многомерный

#### 8

In [51]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [57]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [58]:
v = np.vstack((a, b))
v, v.size

(array([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 10)

#### 9

In [67]:
a = np.arange(12)
a.resize(4, 3)
at = a.transpose()
B = a.dot(at)
B.shape

(4, 4)

In [68]:
np.linalg.matrix_rank(B)

2

In [69]:
np.linalg.det(B)

0.0

##### Определитель матрицы B равен 0 обратную матрицу вычислить нельзя.

#### 10