In [1]:
import numpy as np
import pandas as pd

#### №10

In [42]:
np.random.seed(seed=42)

#### №11

In [39]:
eggs = np.random.randint(0, 16, 16)
eggs

array([ 1,  0, 15,  6,  6, 13,  7,  4,  2, 11,  7,  5, 10,  2,  0,  2])

#### №12

In [44]:
C = eggs.reshape(4, 4)
C 

array([[ 1,  0, 15,  6],
       [ 6, 13,  7,  4],
       [ 2, 11,  7,  5],
       [10,  2,  0,  2]])

In [46]:
C = C.dot(10)
C

array([[ 10,   0, 150,  60],
       [ 60, 130,  70,  40],
       [ 20, 110,  70,  50],
       [100,  20,   0,  20]])

In [47]:
B = np.array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [49]:
D = np.add(B, C)
D

array([[ 15,  14, 173,  92],
       [ 74, 180, 156, 162],
       [ 43, 196, 219, 262],
       [132, 142, 212, 322]])

In [54]:
np.linalg.det(D), np.linalg.matrix_rank(D)

(297540599.99999994, 4)

In [56]:
D_inv = np.linalg.inv(D)

In [59]:
D_inv

array([[ 0.00116697,  0.01112682, -0.01462731,  0.00597034],
       [-0.00382099,  0.00669294,  0.00213638, -0.00401384],
       [ 0.00822725,  0.0038298 , -0.00245029, -0.00228372],
       [-0.00421005, -0.01003433,  0.00666739,  0.00393177]])

#### №13

In [68]:
D_inv = np.where(D_inv < 0, 0, 1)
D_inv

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [67]:
E = np.where(D_inv == 0, C, B)
E

array([[  5,  14, 150,  32],
       [ 60,  50,  86,  40],
       [ 23,  86,  70,  50],
       [100,  20, 212, 302]])